const MAPS = {
  SET_TEMP: 'SET_TEMP',
  INITIALIZE_STORE: 'INITIALIZE_STORE',
  GET_CURRENT_CITY_LOAD: 'GET_CURRENT_CITY_LOAD',
  GET_CURRENT_CITY_RES: 'GET_CURRENT_CITY_RES',
  GET_CURRENT_CITY_ERR: 'GET_CURRENT_CITY_ERR',
  GET_SEARCH_CITY_LOAD: 'GET_SEARCH_CITY_LOAD',
  GET_SEARCH_CITY_RES: 'GET_SEARCH_CITY_RES',
  GET_SEARCH_CITY_ERR: 'GET_SEARCH_CITY_ERR',
  GET_NEWS_LOAD: 'GET_NEWS_LOAD',
  GET_NEWS_RES: 'GET_NEWS_RES',
  GET_NEWS_ERR: 'GET_NEWS_ERR',
  GET_QUOTE_LOAD: 'GET_QUOTE_LOAD',
  GET_QUOTE_RES: 'GET_QUOTE_RES',
  GET_QUOTE_ERR: 'GET_QUOTE_ERR',
  SET_CITIES: 'SET_CITIES',
  REMOVE_CITY: 'REMOVE_CITY'
}

export default {
  ...MAPS
}
